cask_args appdir: '/Applications'

tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'starkandwayne/cf'
tap 'weaveworks/tap'

brew 'ansible'
brew 'ansible-lint'
brew 'awscli'
brew 'bash-completion'
brew 'curl'
brew 'coreutils'
brew 'go'
brew 'docker-credential-helper-ecr'
brew 'fzf'
brew 'git'
brew 'gnupg'
brew 'hh'
brew 'hub'
brew 'istioctl'
brew 'jq'
brew 'kafka'
brew 'kubernetes-cli'
brew 'kops'
brew 'kubernetes-helm'
brew 'kubespy'
brew 'kustomize'
brew 'nmap'
brew 'packer'
brew 'pipenv'
brew 'pv'
brew 'python'
brew 'terraform-docs'
brew 'tfenv'
brew 'tflint'
brew 'tmux'
brew 'tree'
brew 'watch'

cask 'alfred'
cask 'dash'
cask 'docker'
cask 'spotify'
cask 'the-unarchiver'
cask 'vagrant'
cask 'virtualbox'


